---
apiVersion: v1
kind: Service
metadata:
  name: webService
  namespace: dev-namespace
spec:
  selector:
    app: webapp
  ports:
    - protocal: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

