---
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: dev-namespace
  labels:
    app: webapp
    tier: middleware
spec:
  nodeSelector:
    disktype: ssd
  volumes:
    - name: dev-volume
      emptyDir: {}
  containers:
    - name: mw-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: dev-volume
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 15
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 20
  initContainers:
    - name: init-service
      image: busybox
      command: ['sh', '-c', 'echo App is starting && sleep 5']
      volumeMounts:
        - mountPath: /use/share/nginx/html
          name: dev-volume










