---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dev-replicaset
  labels:
    app: web-app
  spec:
    replicas: 4
    selector:
      matchLabels:
        app: web-app
    template:
      metadata:
        labels:
          app: web-app
          NameSpace: dev-namespace
      spec:
        nodeSelector:
          disktype: ssd
        toleration:
          - key: "key1"
            operator: "Equal"
            value: "value1"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/e2e-az-name
                    operator: In
                    values:
                      - e2e-az1
                      - e2e-az2
        serviceAccountName: dev-service-account
        volumes:
        - name: dev-volume
          emptyDir: {}
        containers:
          - name: mw-container
            image: nginx
            ports:
              - containerPort: 80
            volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: dev-volume
            readinessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 30
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 15
              periodSeconds: 30
